[tool.flake8]
# extend-ignore = ['E501']
max-line-length = 88

[tool.mypy]
warn_return_any = true
disallow_untyped_calls = true

[tool.pytest.ini_options]
addopts = "--doctest-modules"

[tool.pylint]
# disable = ["missing-function-docstring", "missing-class-docstring"]

